plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.4'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'org.sonarqube' version '4.4.1.3373'
    id 'jacoco'
}

group = 'co.edu.uniajc'
version = '0.0.1-SNAPSHOT'
description = 'Sistema de gestión y relación con los clientes'

java {
    toolchain { languageVersion = JavaLanguageVersion.of(17) }
}

configurations {
    compileOnly { extendsFrom annotationProcessor }
}

repositories { mavenCentral() }

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.hibernate.validator:hibernate-validator'  // provider de Bean Validation
    implementation 'org.flywaydb:flyway-core'
    implementation 'org.springframework.security:spring-security-crypto'

    implementation 'com.mysql:mysql-connector-j'
    implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.13"

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

springBoot {
    // Ajusta al paquete exacto donde quedó tu clase main:
    mainClass = 'co.edu.uniajc.crm.CrmApplication'
}

tasks.named('test') {
    useJUnitPlatform()
    finalizedBy 'jacocoTestReport'
}

jacoco { toolVersion = '0.8.11' }

jacocoTestReport {
    dependsOn test
    reports {
        xml.required = true
        csv.required = false
        html.required = true
    }
}
sourceSets {
    main {
        java {
            // incluye tu carpeta 'java' actual y la estándar por si luego migras
            srcDirs = ['java', 'src/main/java']
        }
        resources {
            // incluye tu carpeta 'resources' actual y la estándar
            srcDirs = ['resources', 'src/main/resources']
        }
    }
    test {
        java { srcDirs = ['src/test/java'] }
        resources { srcDirs = ['src/test/resources'] }
    }
}


sonar {
    properties {
        property "sonar.host.url", "https://sonarcloud.io"
        property "sonar.organization", "julian022"
        property "sonar.projectKey", "julian022_Boossteam"
        property "sonar.junit.reportPaths", "build/test-results/test"
        property "sonar.coverage.jacoco.xmlReportPaths", "build/reports/jacoco/test/jacocoTestReport.xml"
    }
}
