spring.application.name=CRM

spring.datasource.url=jdbc:mysql://ec2-3-16-111-24.us-east-2.compute.amazonaws.com:3306/boossteam_db
#spring.datasource.url=jdbc:mysql://127.0.0.1:3306/boossteam_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=bossteam
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#spring.datasource.url=jdbc:mysql://127.0.0.1:3306/bossteam
#spring.datasource.username=bossteam
#spring.datasource.password=bossteam
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=false

# Swagger-UI (springdoc)
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Puerto del servidor
server.port=8089
server.address=0.0.0.0
