spring.application.name=CRM
server.port=8089

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/bossteam?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Bogota
spring.datasource.username=root
spring.datasource.password=superseguro123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=false

# Desactiva Flyway mientras no tengas migraciones
spring.flyway.enabled=false

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.swagger-ui.operationsSorter=method
